// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	"context"

	cassandra "github.com/Netcracker/qubership-cassandra-dbaas-adapter/go/impl/cassandra"
	mock "github.com/stretchr/testify/mock"
)

// CassandraService is an autogenerated mock type for the CassandraService type
type CassandraService struct {
	mock.Mock
}

func (_m *CassandraService) EnsureMetadataTable(ctx context.Context, session cassandra.Session, dbName string) error {
	ret := _m.Called(session, dbName)

	var r0 error
	if rf, ok := ret.Get(0).(func(cassandra.Session, string) error); ok {
		r0 = rf(session, dbName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateKeyspace provides a mock function with given fields: session, dbName, settings
func (_m *CassandraService) CreateKeyspace(ctx context.Context, session cassandra.Session, dbName string, settings string) error {
	ret := _m.Called(session, dbName, settings)

	var r0 error
	if rf, ok := ret.Get(0).(func(cassandra.Session, string, string) error); ok {
		r0 = rf(session, dbName, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRole provides a mock function with given fields: session, role, password
func (_m *CassandraService) CreateRole(ctx context.Context, session cassandra.Session, role string, password string) error {
	ret := _m.Called(session, role, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(cassandra.Session, string, string) error); ok {
		r0 = rf(session, role, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTable provides a mock function with given fields: session, dbName, tableName
func (_m *CassandraService) CreateTable(ctx context.Context, session cassandra.Session, dbName string, tableName string) error {
	ret := _m.Called(session, dbName, tableName)

	var r0 error
	if rf, ok := ret.Get(0).(func(cassandra.Session, string, string) error); ok {
		r0 = rf(session, dbName, tableName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DropResource provides a mock function with given fields: session, resourceKind, name
func (_m *CassandraService) DropResource(ctx context.Context, session cassandra.Session, resourceKind string, name string) error {
	ret := _m.Called(session, resourceKind, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(cassandra.Session, string, string) error); ok {
		r0 = rf(session, resourceKind, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllRoles provides a mock function with given fields: session
func (_m *CassandraService) GetAllRoles(ctx context.Context, session cassandra.Session) (map[string]bool, error) {
	ret := _m.Called(session)

	var r0 map[string]bool
	if rf, ok := ret.Get(0).(func(cassandra.Session) map[string]bool); ok {
		r0 = rf(session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(cassandra.Session) error); ok {
		r1 = rf(session)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *CassandraService) UpsertMetadataSetting(ctx context.Context, session cassandra.Session, dbName, key string, value string) error {
	ret := _m.Called(session, dbName, key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(cassandra.Session, string, string, string) error); ok {
		r0 = rf(session, dbName, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRolesForKeyspace provides a mock function with given fields: session, keyspace
func (_m *CassandraService) GetRolesForKeyspace(ctx context.Context, session cassandra.Session, keyspace string) (map[string]bool, error) {
	ret := _m.Called(session, keyspace)

	var r0 map[string]bool
	if rf, ok := ret.Get(0).(func(cassandra.Session, string) map[string]bool); ok {
		r0 = rf(session, keyspace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(cassandra.Session, string) error); ok {
		r1 = rf(session, keyspace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GrantPermissions provides a mock function with given fields: session, dbName, role, permissions
func (_m *CassandraService) GrantPermissions(ctx context.Context, session cassandra.Session, dbName string, role string, permissions []string) error {
	ret := _m.Called(session, dbName, role, permissions)

	var r0 error
	if rf, ok := ret.Get(0).(func(cassandra.Session, string, string, []string) error); ok {
		r0 = rf(session, dbName, role, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCassandraService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCassandraService creates a new instance of CassandraService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCassandraService(t mockConstructorTestingTNewCassandraService) *CassandraService {
	mock := &CassandraService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
