// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	cassandra "github.com/Netcracker/qubership-cassandra-dbaas-adapter/go/impl/cassandra"
	mock "github.com/stretchr/testify/mock"
)

// ClusterInterface is an autogenerated mock type for the ClusterInterface type
type ClusterInterface struct {
	mock.Mock
}

// NewSession provides a mock function with given fields:
func (_m *ClusterInterface) NewSession() (cassandra.Session, error) {
	ret := _m.Called()

	var r0 cassandra.Session
	if rf, ok := ret.Get(0).(func() cassandra.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cassandra.Session)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClusterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewClusterInterface creates a new instance of ClusterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClusterInterface(t mockConstructorTestingTNewClusterInterface) *ClusterInterface {
	mock := &ClusterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
