// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	cassandra "github.com/Netcracker/qubership-cassandra-dbaas-adapter/go/impl/cassandra"
	gocql "github.com/gocql/gocql"

	mock "github.com/stretchr/testify/mock"
)

// CassandraConfiguration is an autogenerated mock type for the CassandraConfiguration type
type CassandraConfiguration struct {
	mock.Mock
}

// GetCluster provides a mock function with given fields: keyspace, consistency
func (_m *CassandraConfiguration) GetCluster(keyspace string, consistency gocql.Consistency) cassandra.ClusterInterface {
	ret := _m.Called(keyspace, consistency)

	var r0 cassandra.ClusterInterface
	if rf, ok := ret.Get(0).(func(string, gocql.Consistency) cassandra.ClusterInterface); ok {
		r0 = rf(keyspace, consistency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cassandra.ClusterInterface)
		}
	}

	return r0
}

// GetDefaultTopology provides a mock function with given fields:
func (_m *CassandraConfiguration) GetDefaultTopology() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHost provides a mock function with given fields:
func (_m *CassandraConfiguration) GetHost() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPort provides a mock function with given fields:
func (_m *CassandraConfiguration) GetPort() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetUser provides a mock function with given fields:
func (_m *CassandraConfiguration) GetUser() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsTLSEnabled provides a mock function with given fields:
func (_m *CassandraConfiguration) IsTLSEnabled() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewCassandraConfiguration interface {
	mock.TestingT
	Cleanup(func())
}

// NewCassandraConfiguration creates a new instance of CassandraConfiguration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCassandraConfiguration(t mockConstructorTestingTNewCassandraConfiguration) *CassandraConfiguration {
	mock := &CassandraConfiguration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
