// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	cassandra "github.com/Netcracker/qubership-cassandra-dbaas-adapter/go/impl/cassandra"
	mock "github.com/stretchr/testify/mock"
)

// QueryInterface is an autogenerated mock type for the QueryInterface type
type QueryInterface struct {
	mock.Mock
}

// Exec provides a mock function with given fields: panicIfError
func (_m *QueryInterface) Exec(panicIfError bool) error {
	ret := _m.Called(panicIfError)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(panicIfError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Iter provides a mock function with given fields:
func (_m *QueryInterface) Iter() cassandra.IterInterface {
	ret := _m.Called()

	var r0 cassandra.IterInterface
	if rf, ok := ret.Get(0).(func() cassandra.IterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cassandra.IterInterface)
		}
	}

	return r0
}

type mockConstructorTestingTNewQueryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueryInterface creates a new instance of QueryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueryInterface(t mockConstructorTestingTNewQueryInterface) *QueryInterface {
	mock := &QueryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
