// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	cassandra "github.com/Netcracker/qubership-cassandra-dbaas-adapter/go/impl/cassandra"
	gocql "github.com/gocql/gocql"

	mock "github.com/stretchr/testify/mock"
)

// Session is an autogenerated mock type for the Session type
type Session struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Session) Close() {
	_m.Called()
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *Session) Query(_a0 string, _a1 ...interface{}) cassandra.QueryInterface {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	var r0 cassandra.QueryInterface
	if rf, ok := ret.Get(0).(func(string, ...interface{}) cassandra.QueryInterface); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cassandra.QueryInterface)
		}
	}

	return r0
}

// SetConsistency provides a mock function with given fields: consistency
func (_m *Session) SetConsistency(consistency gocql.Consistency) {
	_m.Called(consistency)
}

type mockConstructorTestingTNewSession interface {
	mock.TestingT
	Cleanup(func())
}

// NewSession creates a new instance of Session. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSession(t mockConstructorTestingTNewSession) *Session {
	mock := &Session{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
