// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

// import (
// 	cassandra "github.com/Netcracker/qubership-cassandra-operator/pkg/impl/utils/cassandra"
// 	core "github.com/Netcracker/qubership-nosqldb-operator-core/pkg/core"

// 	mock "github.com/stretchr/testify/mock"

// 	v1 "k8s.io/api/core/v1"
// )

// // CassandraUtils is an autogenerated mock type for the CassandraUtils type
// type CassandraUtils struct {
// 	mock.Mock
// }

// // CheckLogin provides a mock function with given fields: ctx, username, password
// func (_m *CassandraUtils) CheckLogin(ctx core.ExecutionContext, username string, password string) bool {
// 	ret := _m.Called(ctx, username, password)

// 	if len(ret) == 0 {
// 		panic("no return value specified for CheckLogin")
// 	}

// 	var r0 bool
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext, string, string) bool); ok {
// 		r0 = rf(ctx, username, password)
// 	} else {
// 		r0 = ret.Get(0).(bool)
// 	}

// 	return r0
// }

// // CreateUser provides a mock function with given fields: ctx, username, password
// func (_m *CassandraUtils) CreateUser(ctx core.ExecutionContext, username string, password string) error {
// 	ret := _m.Called(ctx, username, password)

// 	if len(ret) == 0 {
// 		panic("no return value specified for CreateUser")
// 	}

// 	var r0 error
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext, string, string) error); ok {
// 		r0 = rf(ctx, username, password)
// 	} else {
// 		r0 = ret.Error(0)
// 	}

// 	return r0
// }

// // ExecuteFlushData provides a mock function with given fields: ctx
// func (_m *CassandraUtils) ExecuteFlushData(ctx core.ExecutionContext) error {
// 	ret := _m.Called(ctx)

// 	if len(ret) == 0 {
// 		panic("no return value specified for ExecuteFlushData")
// 	}

// 	var r0 error
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext) error); ok {
// 		r0 = rf(ctx)
// 	} else {
// 		r0 = ret.Error(0)
// 	}

// 	return r0
// }

// // ExecuteNodetoolCommand provides a mock function with given fields: ctx, command
// func (_m *CassandraUtils) ExecuteNodetoolCommand(ctx core.ExecutionContext, command string) error {
// 	ret := _m.Called(ctx, command)

// 	if len(ret) == 0 {
// 		panic("no return value specified for ExecuteNodetoolCommand")
// 	}

// 	var r0 error
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext, string) error); ok {
// 		r0 = rf(ctx, command)
// 	} else {
// 		r0 = ret.Error(0)
// 	}

// 	return r0
// }

// // FindPodsByLabels provides a mock function with given fields: ctx, labels
// func (_m *CassandraUtils) FindPodsByLabels(ctx core.ExecutionContext, labels map[string]string) (*v1.PodList, error) {
// 	ret := _m.Called(ctx, labels)

// 	if len(ret) == 0 {
// 		panic("no return value specified for FindPodsByLabels")
// 	}

// 	var r0 *v1.PodList
// 	var r1 error
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext, map[string]string) (*v1.PodList, error)); ok {
// 		return rf(ctx, labels)
// 	}
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext, map[string]string) *v1.PodList); ok {
// 		r0 = rf(ctx, labels)
// 	} else {
// 		if ret.Get(0) != nil {
// 			r0 = ret.Get(0).(*v1.PodList)
// 		}
// 	}

// 	if rf, ok := ret.Get(1).(func(core.ExecutionContext, map[string]string) error); ok {
// 		r1 = rf(ctx, labels)
// 	} else {
// 		r1 = ret.Error(1)
// 	}

// 	return r0, r1
// }

// // GetAllCassandraPods provides a mock function with given fields: ctx
// func (_m *CassandraUtils) GetAllCassandraPods(ctx core.ExecutionContext) (*v1.PodList, error) {
// 	ret := _m.Called(ctx)

// 	if len(ret) == 0 {
// 		panic("no return value specified for GetAllCassandraPods")
// 	}

// 	var r0 *v1.PodList
// 	var r1 error
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext) (*v1.PodList, error)); ok {
// 		return rf(ctx)
// 	}
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext) *v1.PodList); ok {
// 		r0 = rf(ctx)
// 	} else {
// 		if ret.Get(0) != nil {
// 			r0 = ret.Get(0).(*v1.PodList)
// 		}
// 	}

// 	if rf, ok := ret.Get(1).(func(core.ExecutionContext) error); ok {
// 		r1 = rf(ctx)
// 	} else {
// 		r1 = ret.Error(1)
// 	}

// 	return r0, r1
// }

// // GetConnectionHosts provides a mock function with given fields: ctx
// func (_m *CassandraUtils) GetConnectionHosts(ctx core.ExecutionContext) []string {
// 	ret := _m.Called(ctx)

// 	if len(ret) == 0 {
// 		panic("no return value specified for GetConnectionHosts")
// 	}

// 	var r0 []string
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext) []string); ok {
// 		r0 = rf(ctx)
// 	} else {
// 		if ret.Get(0) != nil {
// 			r0 = ret.Get(0).([]string)
// 		}
// 	}

// 	return r0
// }

// // GetPodLogs provides a mock function with given fields: pod, ctx, tailLines, previous
// func (_m *CassandraUtils) GetPodLogs(pod *v1.Pod, ctx core.ExecutionContext, tailLines *int64, previous bool) (string, error) {
// 	ret := _m.Called(pod, ctx, tailLines, previous)

// 	if len(ret) == 0 {
// 		panic("no return value specified for GetPodLogs")
// 	}

// 	var r0 string
// 	var r1 error
// 	if rf, ok := ret.Get(0).(func(*v1.Pod, core.ExecutionContext, *int64, bool) (string, error)); ok {
// 		return rf(pod, ctx, tailLines, previous)
// 	}
// 	if rf, ok := ret.Get(0).(func(*v1.Pod, core.ExecutionContext, *int64, bool) string); ok {
// 		r0 = rf(pod, ctx, tailLines, previous)
// 	} else {
// 		r0 = ret.Get(0).(string)
// 	}

// 	if rf, ok := ret.Get(1).(func(*v1.Pod, core.ExecutionContext, *int64, bool) error); ok {
// 		r1 = rf(pod, ctx, tailLines, previous)
// 	} else {
// 		r1 = ret.Error(1)
// 	}

// 	return r0, r1
// }

// // GetReplicationFactor provides a mock function with given fields: ctx
// func (_m *CassandraUtils) GetReplicationFactor(ctx core.ExecutionContext) string {
// 	ret := _m.Called(ctx)

// 	if len(ret) == 0 {
// 		panic("no return value specified for GetReplicationFactor")
// 	}

// 	var r0 string
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext) string); ok {
// 		r0 = rf(ctx)
// 	} else {
// 		r0 = ret.Get(0).(string)
// 	}

// 	return r0
// }

// // IsAllDCsDeployed provides a mock function with given fields: ctx
// func (_m *CassandraUtils) IsAllDCsDeployed(ctx core.ExecutionContext) bool {
// 	ret := _m.Called(ctx)

// 	if len(ret) == 0 {
// 		panic("no return value specified for IsAllDCsDeployed")
// 	}

// 	var r0 bool
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext) bool); ok {
// 		r0 = rf(ctx)
// 	} else {
// 		r0 = ret.Get(0).(bool)
// 	}

// 	return r0
// }

// // NewClusterBuilder provides a mock function with given fields: ctx
// func (_m *CassandraUtils) NewClusterBuilder(ctx core.ExecutionContext) cassandra.ClusterBuilder {
// 	ret := _m.Called(ctx)

// 	if len(ret) == 0 {
// 		panic("no return value specified for NewClusterBuilder")
// 	}

// 	var r0 cassandra.ClusterBuilder
// 	if rf, ok := ret.Get(0).(func(core.ExecutionContext) cassandra.ClusterBuilder); ok {
// 		r0 = rf(ctx)
// 	} else {
// 		if ret.Get(0) != nil {
// 			r0 = ret.Get(0).(cassandra.ClusterBuilder)
// 		}
// 	}

// 	return r0
// }

// // RunSshOnPod provides a mock function with given fields: pod, ctx, cmd
// func (_m *CassandraUtils) RunSshOnPod(pod *v1.Pod, ctx core.ExecutionContext, cmd string) (string, error) {
// 	ret := _m.Called(pod, ctx, cmd)

// 	if len(ret) == 0 {
// 		panic("no return value specified for RunSshOnPod")
// 	}

// 	var r0 string
// 	var r1 error
// 	if rf, ok := ret.Get(0).(func(*v1.Pod, core.ExecutionContext, string) (string, error)); ok {
// 		return rf(pod, ctx, cmd)
// 	}
// 	if rf, ok := ret.Get(0).(func(*v1.Pod, core.ExecutionContext, string) string); ok {
// 		r0 = rf(pod, ctx, cmd)
// 	} else {
// 		r0 = ret.Get(0).(string)
// 	}

// 	if rf, ok := ret.Get(1).(func(*v1.Pod, core.ExecutionContext, string) error); ok {
// 		r1 = rf(pod, ctx, cmd)
// 	} else {
// 		r1 = ret.Error(1)
// 	}

// 	return r0, r1
// }

// // NewCassandraUtils creates a new instance of CassandraUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// // The first argument is typically a *testing.T value.
// func NewCassandraUtils(t interface {
// 	mock.TestingT
// 	Cleanup(func())
// }) *CassandraUtils {
// 	mock := &CassandraUtils{}
// 	mock.Mock.Test(t)

// 	t.Cleanup(func() { mock.AssertExpectations(t) })

// 	return mock
// }
